
### Add a New Post
POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "title",
    "content": "content",
    "owner": "Hilaa"
}

### Get Post by ID
GET http://localhost:3000/post/678616f3e56d98efeb7e5fee

### Get All Posts
GET http://localhost:3000/post/all

### Get Posts by Sender
GET http://localhost:3000/post/?senderId=Hilaa

### Update a Post
PUT http://localhost:3000/post/67839f695f21a781fa13d1a4
Content-Type: application/json

{
    "title": "Updated Title",
    "content": "Updated content",
    "owner": "Updated Owner"
}

### Delete a Post
DELETE http://localhost:3000/post/delete/6780eee9b8af99ae8ce4deed






### Create a new comment
POST http://localhost:3000/comment
Content-Type: application/json

{
  "content": "comment content 2",
  "postId": "67839f725f21a781fa13d1a6",
  "owner": "Hila"
}



### Get all comments
GET http://localhost:3000/comment




### Get comments by Post ID
GET http://localhost:3000/comment/67839f725f21a781fa13d1a6



### Get a comment by ID
GET http://localhost:3000/comment/6783ab3225c2eaa51eaa1f48



### Update a comment by ID
PUT http://localhost:3000/comment/6783aa6825c2eaa51eaa1f3c
Content-Type: application/json

{
  "content": "Updated comment to DELETE",
  "owner": "user123"
}



### Delete a comment by ID
DELETE http://localhost:3000/comment/6783ab3225c2eaa51eaa1f48






